{
 "title": "WebAPI",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": "http_requests_received_total" }
  ]
 },
 "panels": [
  {
   "title": "Status code / min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Req/min" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (irate(http_requests_received_total{service=\"$service\"}[1m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Memory usage per instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{service=\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.98, sum(rate(http_request_duration_seconds_bucket{service=\"$service\"}[5m])) by (le))",
     "legendFormat": "98 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service=\"$service\"}[5m])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{service=\"$service\"}[5m])) by (le))",
     "legendFormat": "90 percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{service=\"$service\"}[5m])) by (le))",
     "legendFormat": "50 percentile"
    }
   ]
  },
  {
   "title": "CPU usage per instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(process_cpu_seconds_total{service=\"$service\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Controller request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (controller) (rate(http_requests_received_total{service=\"$service\", controller!=\"\"}[5m]))",
     "legendFormat": "{{controller}}"
    }
   ]
  }
 ]
}